#!/bin/bash
# Copies the repository files to the working kernel directory
# This is used on a freshly untarred kernel

export FROM=/ebtables-cvs/ebtables2/
export TO=/usr/src/ebt2.0pre11

mkdir -p $TO/net/bridge/netfilter
mkdir -p $TO/include/netfilter_bridge
cp -r -f $FROM/br-nf-bds/linux/* $TO/
cp -r -f $FROM/kernel/linux/* $TO/
