#!/bin/bash
# Copies the repository files to the working kernel directory
# This is used on a freshly untarred kernel

export FROM=/ebtables-cvs/ebtables2/
export TO=/usr/src/linux

mkdir -p $FROM/linux/net/bridge/netfilter
mkdir -p $FROM/linux/include/netfilter_bridge
cp -r -f $FROM/br-nf-bds/linux/* $TO/
cp -r -f $FROM/kernel/linux/* $TO/
