#!/bin/bash
#This needs to be executed from within the work version
currdir=.
olddir=../ebtables2/userspace/ebtables2
regexp="find $currdir -name \"*.c\";"
regexp=$regexp"find $currdir -name \"*.h\";find $currdir -name \"Makefile\";"
regexp=$regexp"find $currdir -name \"ethertypes\";find $currdir -name \"ChangeLog\";"
regexp=$regexp"find $currdir -name \"COPYING\";find $currdir -name \"INSTALL\";"
regexp=$regexp"find $currdir -name \"THANKS\";find $currdir -name \"perf_test\" -type f;"
for a in `eval $regexp`
do
  diff -purN $olddir/$a $currdir/$a
done